{% set version = "0.1.3" %}

package:
  name: dictpath
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/d/dictpath/dictpath-{{ version }}.tar.gz
    sha256: 751cde3b76b176d25f961b90c423a11a4d5ede9bd09ab0d64a85abb738c190d8
  - folder: src
    url: https://github.com/p1c2u/dictpath/archive/refs/tags/{{ version }}.tar.gz
    sha256: 09d918e9d01d9354a580b68685ae13e902bcf02c6080337f454ae161c70806f1

build:
  number: 1
  noarch: python
  script:
    - cd dist 
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - six

test:
  source_files:
    - src/tests
  requires:
    - mock
    - pip
    - pytest
    - pytest-cov
    - python {{ python_min }}
  imports:
    - dictpath
  commands:
    - pip check
    - cd src 
    - coverage run --source=dictpath --branch -m pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered --fail-under 79

about:
  home: https://github.com/p1c2u/dictpath
  summary: Object-oriented dictionary paths
  license: Apache-2.0
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
